server:
  port: 8080
  servlet:
    context-path: /api/v1
  forward-headers-strategy: framework

spring:
  application:
    name: fortune-cookie  # 프로젝트명에 맞게
  profiles:
    active: local
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5 # 유휴 연결 5개는 항상 유지
      connection-timeout: 30000
      validation-timeout: 5000
      idle-timeout: 600000      # 10분 (keepalive보다 길게)
      keepalive-time: 120000  # 2분마다 ping으로 연결 살리기
      max-lifetime: 1800000      # 30분마다 연결 순환

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    property-naming-strategy: LOWER_CAMEL_CASE
    time-zone: Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: update   # 개발용
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

springdoc:
  paths-to-match: /**
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.psytest: DEBUG   # ← 실제 base package로 교체
